package world.sc2.shadowcraftrelics.relics.on_hit_ground;

import org.bukkit.entity.LivingEntity;
import world.sc2.shadowcraftrelics.events.PlayerHitGroundEvent;
import world.sc2.shadowcraftrelics.relics.Relic;

/**
 * An interface that represents a {@link Relic} with functionality that triggers whenever a {@link LivingEntity} wearing
 * this {@link Relic} hits the ground in an {@link PlayerHitGroundEvent}.
 */
public interface TriggerOnEntityHitGroundRelic {

    /**
     * This method is called whenever it is determined that a {@link LivingEntity} has hit the ground while wearing this
     * {@link Relic}.
     * @param event The instance of {@link PlayerHitGroundEvent} generated by the Entity hitting the ground.
     */
    void onHitGround(PlayerHitGroundEvent event);

}
