name: ShadowcraftRelics
version: '${project.version}'
main: world.sc2.shadowcraftrelics.ShadowcraftRelics
api-version: '1.19'
author: "ChillyTheEevee"
commands:
  relics:
    description: Base command for the ShadowcraftRelics plugin
    usage: /relics <subcommand>
    aliases:
      - shadowcraftrelics

permissions:
  shadowcraftrelics.help:
    description: Grants the player the ability to use the /relics help command
    default: op
  shadowcraftrelics.reload:
    description: Grants the player the ability to use the /relics reload command
    default: op
  shadowcraftrelics.giverelictag:
    description: Grants the player the ability to use the /relics giverelictag command
    default: op
  shadowcraftrelics.setpurgerstates:
    description: Grants the player the ability to use the /relics setpurgerstates command
    default: op