package world.sc2.shadowcraftrelics.relics.morphable_relic;

import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import world.sc2.config.Config;
import world.sc2.config.ConfigManager;
import world.sc2.nbt.NBTTag;
import world.sc2.shadowcraftrelics.events.RelicMorphEvent;
import world.sc2.shadowcraftrelics.relics.on_interact.TriggerOnInteractRelic;

/**
 * A {@link ConfigMorphableRelic} that has the special property of switching states on right click.
 */
public class ForeignForgedBlade extends ConfigMorphableRelic implements TriggerOnInteractRelic {

    /**
     * @param name             The name of the Relic
     * @param config           The {@link Config} assigned to the Relic
     * @param configManager    The instance of {@link ConfigManager} generated by the plugin
     * @param morphConfigIDTag The NBT tag in which the ConfigMorphableRelic's morph config identifier is stored
     * @param morphIndexTag    The NBT tag in which the ConfigMorphableRelic's index is stored
     */
    public ForeignForgedBlade(String name, Config config, ConfigManager configManager, NBTTag<String, String> morphConfigIDTag, NBTTag<Integer, Integer> morphIndexTag) {
        super(name, config, configManager, morphConfigIDTag, morphIndexTag);
    }

    @Override
    public void onInteract(PlayerInteractEvent event) {
        Player player = event.getPlayer();

        EquipmentSlot equipmentSlot = EquipmentSlot.HAND;
        ItemStack currentForeignForgedBlade = player.getInventory().getItem(equipmentSlot);

        if (event.getAction().isRightClick()) {
            RelicMorphEvent relicMorphEvent = new RelicMorphEvent(player, currentForeignForgedBlade, equipmentSlot);
            morph(relicMorphEvent);
        }
    }

}
