description: "Creates a ConfigMorphableRelic using the items in the sender's hotbar as the list. Debug command."
usage: "/createconfigmorphablerelicchain"
permission:
  - "shadowcraftrelics.createconfigmorphablerelicchain"

messages:
  success: "&aSuccessfully created a ConfigMorphableRelic from the items provided!"

  warning_non_player_sender: "&cOnly players can use this command!"
  warning_invalid_number_of_items: "&cYou must have at least two items to merge into one in your hotbar."